use_frameworks!

target 'Fruits_Example' do
  pod 'Fruits', :path => '../'

  target 'Fruits_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
